[project]
name = "docstring-unity-test-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astor>=0.8.1",
    "jupyterlab>=4.4.10",
    "openai>=2.6.1",
    "python-dotenv>=1.1.1",
]
